name: i3_workspace_groups
channels:
  - conda-forge
  - defaults
dependencies:
  # NOTE: The networkx dep which is transitively pulled by pytype doesn't
  # support python 3.8 in new versions, so the requirements.txt file generated
  # with python 3.8 doesn't work with 3.7.
  - python=3.7
  - pip
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
